name: Build and Deploy MMAEagles new Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.0.0

      - name: Install Angular global
        run: npm install -g @angular/cli@18.0.0

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npx ng build --base-href /MMAEagles/

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/MMAEagles/browser --name="Denis Micheletti" --email=denis.micheletti@gmail.com --no-silent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.PUBLISH_GH_PAGE }}
